name: dashboard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  breakpoint: ^1.2.0
  freezed: ^2.1.0+1
  getwidget: ^3.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.9
  go_router: ^4.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true